// <auto-generated />
using System;
using AnotadorGymApp.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnotadorGymApp.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.DiaEntrenamiento", b =>
                {
                    b.Property<int>("DiaEntrenamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volumen")
                        .HasColumnType("REAL");

                    b.HasKey("DiaEntrenamientoId");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("DiasEntrenamientos");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Iniciar")
                        .HasColumnType("REAL");

                    b.Property<double?>("Mejor")
                        .HasColumnType("REAL");

                    b.Property<int>("MusculoPrimarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Ultimo")
                        .HasColumnType("REAL");

                    b.HasKey("EjercicioId");

                    b.HasIndex("GrupoMuscularId");

                    b.HasIndex("MusculoPrimarioId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.GrupoMuscular", b =>
                {
                    b.Property<int>("GrupoMuscularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GrupoMuscularId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("GrupoMusculares");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Musculo", b =>
                {
                    b.Property<int>("MusculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusculoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Musculos");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RegistroEjercicio", b =>
                {
                    b.Property<int>("RegistroEjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaEntrenamientoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistroEjercicioId");

                    b.HasIndex("DiaEntrenamientoId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RegistrosEjercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RegistroSerie", b =>
                {
                    b.Property<int>("RegistroSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kilos")
                        .HasColumnType("REAL");

                    b.Property<int>("RegistroEjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistroSerieId");

                    b.HasIndex("RegistroEjercicioId");

                    b.ToTable("RegistrosSeries");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaDia", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaIdUI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRutinaDia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemanaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiaId");

                    b.HasIndex("SemanaId");

                    b.ToTable("RutinaDias");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaEjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("DiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroEjercicio")
                        .HasColumnType("INTEGER");

                    b.HasKey("RutinaEjercicioId");

                    b.HasIndex("DiaId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaSemana", b =>
                {
                    b.Property<int>("SemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RutinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SemanaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaSemanas");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaSeries", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descanso")
                        .HasColumnType("TEXT");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoSerie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Porcentaje1RM")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("SerieId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RutinaSeries");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Rutinas", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dificultad")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrecuenciaPorGrupo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TiempoPorSesion")
                        .HasColumnType("TEXT");

                    b.HasKey("RutinaId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("EjercicioMusculo", b =>
                {
                    b.Property<int>("EjerciciosSecundariosEjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusculosSecundariosMusculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EjerciciosSecundariosEjercicioId", "MusculosSecundariosMusculoId");

                    b.HasIndex("MusculosSecundariosMusculoId");

                    b.ToTable("ExerciseSecondaryMuscles", (string)null);
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Ejercicio", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Ejercicios")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Models.Entities.Musculo", "MusculoPrimario")
                        .WithMany("EjerciciosPrimarios")
                        .HasForeignKey("MusculoPrimarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");

                    b.Navigation("MusculoPrimario");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RegistroEjercicio", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.DiaEntrenamiento", "DiaEntrenamiento")
                        .WithMany("RegistroEjercicios")
                        .HasForeignKey("DiaEntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Models.Entities.Ejercicio", "Ejercicio")
                        .WithMany("RegistrosEjercicio")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaEntrenamiento");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RegistroSerie", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.RegistroEjercicio", "RegistroEjercicio")
                        .WithMany("RegistroSeries")
                        .HasForeignKey("RegistroEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroEjercicio");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaDia", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.RutinaSemana", "Semana")
                        .WithMany("Dias")
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semana");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaEjercicio", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.RutinaDia", "Dia")
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Models.Entities.Ejercicio", "Ejercicio")
                        .WithMany("RutinasEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dia");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaSemana", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.Rutinas", "Rutina")
                        .WithMany("Semanas")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaSeries", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.RutinaEjercicio", "RutinaEjercicio")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaEjercicio");
                });

            modelBuilder.Entity("EjercicioMusculo", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Models.Entities.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjerciciosSecundariosEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Models.Entities.Musculo", null)
                        .WithMany()
                        .HasForeignKey("MusculosSecundariosMusculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.DiaEntrenamiento", b =>
                {
                    b.Navigation("RegistroEjercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Ejercicio", b =>
                {
                    b.Navigation("RegistrosEjercicio");

                    b.Navigation("RutinasEjercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.GrupoMuscular", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Musculo", b =>
                {
                    b.Navigation("EjerciciosPrimarios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RegistroEjercicio", b =>
                {
                    b.Navigation("RegistroSeries");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaDia", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaEjercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.RutinaSemana", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Models.Entities.Rutinas", b =>
                {
                    b.Navigation("Semanas");
                });
#pragma warning restore 612, 618
        }
    }
}
